export const queries = {
    getAllproducts : 'SELECT * FROM COTIZACIONES',
    createProduct : 'INSERT INTO COTIZACIONES(NOMBRECOMPLETO,TIPOCOTIZACION,ESTADO) VALUES (@A1,@A2,@A3)',
    getProductsById : 'SELECT * FROM COTIZACIONES WHERE IDCOTIZACION = @ID',
    deleteProductById : 'DELETE FROM COTIZACIONES WHERE IDCOTIZACION = @ID',
    getTotal : 'SELECT COUNT(*) FROM COTIZACIONES',
    UpdateProduct : 'UPDATE COTIZACIONES SET  NOMBRECOMPLETO = @NOMBRECOMPLETO,TIPOCOTIZACION = @TIPOCOTIZACION,ESTADO=@ESTADO WHERE  IDCOTIZACION = @ID',
    DetallesProdudct: 'SELECT * FROM COTIZACIONESDETALLES WHERE IDCOTIZACION = @ID',
    UpdateStatus: 'UPDATE COTIZACIONES SET ESTADO = @ESTADO  WHERE  IDCOTIZACION = @ID',
    UpdateDetalle: 'UPDATE COTIZACIONESDETALLES SET APLICA = @APLICA WHERE IDCOTIZACIONDETALLES = @IDDETALLE',
    imagenesAlmacenes : 'SELECT * FROM IMAGENESALMACEN',
    almacenes: 'SELECT DISTINCT IDALMACEN FROM IMAGENESALMACEN',
    contratos: 'SELECT * FROM CONTRATOS LEFT JOIN TIEMPODEPAGOS ON TIEMPODEPAGOS.IDTIEMPODEPAGO = CONTRATOS.IDPERIOCIDADDEPAGO WHERE IDCONTRATO = @ID',
    firmaContrato : 'UPDATE CONTRATOS SET FIRMA = @FIRMA,TIENEFIRMA = @TIENEFIRMA WHERE IDCONTRATO = @ID'
}